/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:201583:
  appc.background(230);
} //_CODE_:window1:201583:

public void phaseHandler(GCustomSlider source, GEvent event) { //_CODE_:moonPhase:769696:
  println("moonPhase - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:moonPhase:769696:

public void zoomHandler(GCustomSlider source, GEvent event) { //_CODE_:zoom:868503:
  println("zoom - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:zoom:868503:

public void button1_click1(GButton source, GEvent event) { //_CODE_:lunarEclipse:944604:
  println("lunarEclipse - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:lunarEclipse:944604:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 500, 120, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  moonPhase = new GCustomSlider(window1, 17, 15, 100, 40, "grey_blue");
  moonPhase.setLimits(0.5, 0.0, 1.0);
  moonPhase.setNumberFormat(G4P.DECIMAL, 2);
  moonPhase.setOpaque(false);
  moonPhase.addEventHandler(this, "phaseHandler");
  zoom = new GCustomSlider(window1, 128, 19, 100, 40, "grey_blue");
  zoom.setLimits(0.5, 0.0, 1.0);
  zoom.setNumberFormat(G4P.DECIMAL, 2);
  zoom.setOpaque(false);
  zoom.addEventHandler(this, "zoomHandler");
  lunarEclipse = new GButton(window1, 8, 67, 80, 30);
  lunarEclipse.setText("Face text");
  lunarEclipse.addEventHandler(this, "button1_click1");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GCustomSlider moonPhase; 
GCustomSlider zoom; 
GButton lunarEclipse; 
